pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                // Install Pygame
                sh "pip install pygame"
                
                // Run Python script with video display
                sh 'xvfb-run -a /usr/bin/python3 main.py'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}